main: com.alpsbte.globalchat.GlobalChat
version: 1.3
api-version: 1.12.2
name: AlpsBTE-GlobalChat
author: R3tuxn

commands:
  gcreload:
    description: Reloads Global-Chat config
    usage: /gcreload