main: com.alpsbte.globalchat.GlobalChat
version: 1.5
api-version: 1.20
name: AlpsBTE-GlobalChat
author: R3tuxn

commands:
  gcreload:
    description: Reloads Global-Chat config
    usage: /gcreload